#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tie-Hash-Sorted
version:      0.09
version_from: Sorted.pm
installdirs:  site
requires:
    Carp:                          0
    strict:                        0
    UNIVERSAL:                     0
    vars:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
